### ISSUE TITLE
warning: this clause cannot match because a previous clause at line ... always matches

### ISSUE THREAD

**Issue by mspanc** [sproutapp/pavlov#36]
When I use `let` I receive one error like this

`test/models/channel/input/stream/rtp_test.exs:1: warning: this clause cannot match because a previous clause at line 174 always matches`

per each `let` used in the test case.

It does not affect running tests but it floods the console.

**Comment by inf0rmer** [comment]
I've also noticed this (it happens in Pavlov's own tests), however I can't figure out the reason behind it. [This other test](https://github.com/sproutapp/microbrew.ex/blob/master/test/agent_test.exs), in a different library that uses Pavlov for testing, also has several `let` definitions but the warnings don't come up there.

I'm still trying to figure out why this happens, any help would be very appreciated :smile:.

**Comment by inf0rmer** [comment]
After banging my head against this problem for some hours, I finally fixed it! The solution is as simple as making the function defined by calling the `let` macro overridable, thus allowing nested modules to override it safely, which stops the unmatchable clause warning.

Thanks for pushing me to finally fix this!

**Comment by inf0rmer** [comment]
I've released version `0.2.3` which fixes this issue, along with some fixes for Elixir 1.0.5 support.

**Comment by mspanc** [comment]
Thank you!
